using System.Linq; // OpenSpace
using Content.Client.UserInterface.Controls;
using Content.Shared._OpenSpace.TTS; // OpenSpace
using Content.Shared.Speech;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration; // OpenSpace
using Robust.Shared.Prototypes;
using Content.Shared.CCVar; // OpenSpace

namespace Content.Client.VoiceMask;

[GenerateTypedNameReferences]
public sealed partial class VoiceMaskNameChangeWindow : FancyWindow
{
    public Action<string>? OnNameChange;
    public Action<string?>? OnVerbChange;
    public Action? OnToggle;
    public Action? OnAccentToggle;
    public Action<string?>? OnVoiceChange; // OpenSpace

    private List<(string, string)> _verbs = new();
    private List<TTSVoicePrototype> _voices = new(); // OpenSpace

    private string? _verb;

    [Dependency] private readonly IPrototypeManager _proto = default!; // OpenSpace
    [Dependency] private readonly IConfigurationManager _cfg = default!; // OpenSpace

    public VoiceMaskNameChangeWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this); // OpenSpace

        NameSelectorSet.OnPressed += _ =>
        {
            OnNameChange?.Invoke(NameSelector.Text);
        };

        SpeechVerbSelector.OnItemSelected += args =>
        {
            OnVerbChange?.Invoke((string?) args.Button.GetItemMetadata(args.Id));
            SpeechVerbSelector.SelectId(args.Id);
        };

        ToggleButton.OnPressed += args => OnToggle?.Invoke();
        ToggleAccentButton.OnPressed += args => OnAccentToggle?.Invoke();

        ReloadVoices(); // OpenSpace
    }

    // OpenSpace edit start
    private void ReloadVoices()
    {
        var ttsEnabled = _cfg.GetCVar(CCVars.TTSEnabled);
        TTSContainer.Visible = ttsEnabled;
        if (!ttsEnabled)
            return;

        _voices = _proto
            .EnumeratePrototypes<TTSVoicePrototype>()
            .OrderBy(o => Loc.GetString(o.Name))
            .OrderBy(o => ((o.Gender == "male") ? 0b01 : 0) + ((o.Gender == "female") ? 0b10 : 0))
            .ToList();

        VoiceSelector.OnItemSelected += args =>
        {
            VoiceSelector.SelectId(args.Id);
            if (VoiceSelector.SelectedMetadata != null)
                OnVoiceChange?.Invoke((string?)VoiceSelector.SelectedMetadata);
        };

        for (var i = 0; i < _voices.Count; i++)
        {
            var name = Loc.GetString(_voices[i].Name);
            VoiceSelector.AddItem(name);
            VoiceSelector.SetItemMetadata(i, _voices[i].ID);
        }
    }

    public void SelectVoice(string? voiceId)
    {
        if (voiceId == null) return;
        for (var i = 0; i < VoiceSelector.ItemCount; i++)
        {
            if (string.Equals(VoiceSelector.GetItemMetadata(i), voiceId))
            {
                VoiceSelector.SelectId(i);
                break;
            }
        }
    }
    // OpenSpace edit end

    public void ReloadVerbs(IPrototypeManager proto)
    {
        foreach (var verb in proto.EnumeratePrototypes<SpeechVerbPrototype>())
        {
            _verbs.Add((Loc.GetString(verb.Name), verb.ID));
        }
        _verbs.Sort((a, b) => a.Item1.CompareTo(b.Item1));
    }

    public void AddVerbs()
    {
        SpeechVerbSelector.Clear();

        AddVerb(Loc.GetString("chat-speech-verb-name-none"), null);
        foreach (var (name, id) in _verbs)
        {
            AddVerb(name, id);
        }
    }

    private void AddVerb(string name, string? verb)
    {
        var id = SpeechVerbSelector.ItemCount;
        SpeechVerbSelector.AddItem(name);
        if (verb is {} metadata)
            SpeechVerbSelector.SetItemMetadata(id, metadata);

        if (verb == _verb)
            SpeechVerbSelector.SelectId(id);
    }

    public void UpdateState(string name, string? verb, bool active, bool accentHide, LocId titleText)
    {
        NameSelector.Text = name;
        _verb = verb;
        ToggleButton.Pressed = active;
        ToggleAccentButton.Pressed = accentHide;
        Title = Loc.GetString(titleText);
        for (int id = 0; id < SpeechVerbSelector.ItemCount; id++)
        {
            if (string.Equals(verb, SpeechVerbSelector.GetItemMetadata(id)))
            {
                SpeechVerbSelector.SelectId(id);
                break;
            }
        }
    }
}
